# Generated by Django 4.2.4 on 2023-09-20 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name=' ادرس ایمیل')),
                ('phone_number', models.CharField(max_length=12, unique=True, verbose_name='شماره تلفن')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='نام کاربری')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False, verbose_name='ادمین')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(blank=True, max_length=28, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('randcode', models.SmallIntegerField()),
                ('expiresion_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعتبار سنجی',
                'verbose_name_plural': 'سرویس اعتبار سنجی',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=11)),
                ('postal_code', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس ها',
            },
        ),
    ]
