# Generated by Django 4.2.4 on 2023-08-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_otp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'اعتبار سنجی', 'verbose_name_plural': 'سرویس اعتبار سنجی'},
        ),
    ]
