# Generated by Django 4.2.4 on 2023-09-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouoonCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('expires', models.DateTimeField()),
                ('amount', models.PositiveIntegerField(default=0)),
                ('description', models.CharField(max_length=70)),
                ('type', models.CharField(choices=[('cent', 'percent'), ('val', 'value')], max_length=5)),
            ],
        ),
    ]
