# Generated by Django 4.2.4 on 2023-09-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_couooncode_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CouoonCode',
            new_name='CouponCode',
        ),
        migrations.AlterModelOptions(
            name='couponcode',
            options={'verbose_name': 'کد تخفیف', 'verbose_name_plural': 'کد تخفیف ها'},
        ),
        migrations.RenameField(
            model_name='couponcode',
            old_name='expires',
            new_name='expire',
        ),
    ]
