# Generated by Django 4.2.4 on 2023-09-24 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
