# Generated by Django 4.2.4 on 2023-09-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
